---

- hosts: kvm-servers
  roles:
    - postfix
    - network
    - motd
  tasks:
    - name: Check for vmx and svm CPU flags
      shell: "grep flags /proc/cpuinfo | egrep -q '(vmx|svm)'"
      changed_when: False

    - name: Install packages for KVM
      yum:
        name: "{{ item }}"
        state: present
        enablerepo: extras
      with_items:
        - libvirt
        - qemu-kvm
        - libvirt-client
        - libvirt-daemon
        - libvirt-daemon-kvm
        - virt-install
        - bridge-utils
        - bind-utils
        - nfs-utils

    - name: Start libvirtd service, load it on boot
      service: name=libvirtd state=started enabled=yes

    - name: Hostfix for broken rpc service file
      lineinfile:
        dest: /usr/lib/systemd/system/rpc-statd.service
        regexp: '^After=network.target'
        line: "After=network.target nss-lookup.target rpcbind.service"
      notify: reload nfs

    - name: Set hostname from inventory
      hostname: name={{ inventory_hostname_short }}

  handlers:
    - name: reload nfs
      service: name=nfs state=restarted
