---

- hosts: kvm-servers
  roles:
    - postfix
    - network
    - motd
  tasks:
    - name: Check for vmx and svm CPU flags
      shell: "grep flags /proc/cpuinfo | egrep -q '(vmx|svm)'"
      changed_when: False

    - name: Install packages for KVM
      yum:
        name: "{{ item }}"
        state: present
        enablerepo: extras
      with_items:
        - libvirt
        - qemu-kvm
        - libvirt-client
        - libvirt-daemon-kvm
        - virt-install
        - bridge-utils
        - bind-utils

    - name: Start libvirtd service, load it on boot
      service: name=libvirtd state=started enabled=yes
