---

- hosts: all
  tasks:
    - name: Install packages on all servers
      apt: name={{ item }} state=present
      with_items:
        - emacs
        - vim

- include: generic.yml
- include: shell-servers.yml
