---

# Do this on all servers in ./inventory
- hosts: all
  roles:
    - ntpd
  tasks:
    - name: Debian | Install packages on all servers
      apt: name={{ item }} state=present
      with_items:
        - emacs
        - vim
        - sharutils
      when: ansible_os_family == "Debian"

    - name: RedHat | Install packages on all servers
      yum: name={{ item }} state=present
      with_items:
        - emacs
        - vim
        - sharutils
      when: ansible_os_family == "RedHat"

# Do this on special groups of servers
- include: playbooks/shell-servers.yml
- include: playbooks/kvm-servers.yml
- include: playbooks/file-servers.yml
