---

# Run a play agains all hosts without facts
- hosts: all
  gather_facts: False
  roles:
    - icinga-checks

# Only run this against managed hosts
- hosts: all:!unmanaged
  roles:
    - ntpd
  tasks:
    - name: Debian | Install packages on all servers
      apt: name={{ item }} state=present
      with_items:
        - emacs
        - vim
        - sharutils
      when: ansible_os_family == "Debian"

    - name: RedHat | Install packages on all servers
      yum: name={{ item }} state=present
      with_items:
        - emacs
        - vim
        - sharutils
      when: ansible_os_family == "RedHat"

# Do this on special groups of servers
- include: playbooks/shellserver/site.yml
- include: playbooks/kvmserver/site.yml
- include: playbooks/fileserver/site.yml
- include: playbooks/lxd/site.yml
