---

- name: Write network configurations for RedHat
  template:
    src: "ifcfg.dev.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.device_name }}"
  with_items: network_config
  when: ansible_os_family == "RedHat"

- name: Write network configuration for Debian
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  when: ansible_os_family == "Debian"

- name: Enable IPv6
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: "^NETWORKING_IPV6"
    line: "NETWORKING_IPV6=yes"
  when: ansible_os_family == "RedHat"
