---

- hosts: kvm-servers
  roles:
    - postfix
    - network
    - motd
  tasks:
    - name: Check for vmx and svm CPU flags
      shell: "grep flags /proc/cpuinfo | egrep -q '(vmx|svm)'"
      changed_when: False

    - name: Install packages for KVM
      yum:
        name: "{{ item }}"
        state: present
        enablerepo: extras
      with_items:
        - libvirt
        - qemu-kvm
        - libvirt-client
        - libvirt-daemon
        - libvirt-daemon-kvm
        - virt-install
        - bridge-utils
        - bind-utils

    - name: Start libvirtd service, load it on boot
      service: name=libvirtd state=started enabled=yes

    - name: Set hostname from inventory
      hostname: name={{ inventory_hostname_short }}

    - name: SELINUX | Set to permissive
      lineinfile:
        dest: /etc/sysconfig/selinux
        regexp: '^SELINUX='
        line: "SELINUX=permissive"

    - name: Deploy hosts
      template:
        src: templates/hosts-kvm.j2
        dest: /etc/hosts

    - name: Deploy qemu.conf
      template:
        src: templates/qemu.conf.j2
        dest: /etc/libvirt/qemu.conf
