---

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Enable glusterd
  service: name=glusterd enabled=yes state=started

- name: Enable glusterfsd
  service: name=glusterfsd enabled=yes state=started
