---

- name: Disable selinux (1/2)
  selinux: policy=targeted state=disabled
  register: selinux_status

- name: Disable selinux (2/2)
  command: setenforce 0
  when: selinux_status|changed

- name: Install gluster applications
  yum: name="{{ item }}"
  with_items:
    - glusterfs-server
    - attr

- name: Make sure we have /etc/sysconfig/i18n
  file: path="{{ item }}" state=touch
  changed_when: False
  with_items:
    - /etc/environment
    - /etc/sysconfig/i18n

- name: Set system LC_NUMERIC to en_US.UTF-8 as a workaround for bug bug-1117951
  lineinfile:
    dest: "{{ item }}"
    regexp: "^LC_NUMERIC"
    line: "LC_NUMERIC=en_US.UTF-8"
  with_items:
    - /etc/environment
    - /etc/sysconfig/i18n

- name: Enable glusterd
  service: name=glusterd enabled=yes state=started

- name: Enable glusterfsd
  service: name=glusterfsd enabled=yes state=started
