---

- name: Disable selinux (1/2)
  selinux: policy=targeted state=disabled
  register: selinux_status

- name: Disable selinux (2/2)
  command: setenforce 0
  when: selinux_status|changed

- name: Install glusterfs-epel repo
  copy: src=glusterfs-epel.repo dest=/etc/yum.repos.d/glusterfs-epel.repo

- name: Import GPG signature for glusterfs-epel
  copy: src=pub.key dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-GLUSTERFS-EPEL

- name: Install gluster applications
  yum: name="{{ item }}"
  with_items:
    - glusterfs-server
    - glusterfs-fuse
    - glusterfs-geo-replication

- name: Enable glusterd
  service: name=glusterd enabled=yes state=started

- name: Enable glusterfsd
  service: name=glusterfsd enabled=yes state=started
